name: EMS-DTR CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate setup
        run: echo "✅ EMS+DTR project repo check passed"
